name = "Rcl"
uuid = "78a8c452-60eb-11e8-3cb2-e7ea7ae9c7f8"
authors = ["Nicu Stiurca <supernic2002@gmail.com>"]
version = "0.1.0"

[deps]
Blobs = "2063b8be-a4ad-11e8-1fb9-93d01944c8ed"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
